print("Invierte Datos")
print("El programa dado un conjunto de datos de entrada invierte el orden de los mismos cuando los imprime")
A= input("Dame el valor de A:")
B= input("Dame el valor de B:")
C= input("Dame el valor de C:")
D= input("Dame el valor de D:")
print(f"El orden inverso de los valores es: { D }, { C }, { B }, { A }")
